### ISSUE TITLE
Internal server error 500 when linking an account with Cardmarket.

### ISSUE THREAD

**Issue by barning** [Cardmonitor/cardmonitor#164]
I can't link my Cardmarket account to my account on the instance you are hosting. I only get a 500 Internal Server Error.

**Comment by Tanariel** [comment]
Same problem here :(

**Comment by danielsundermeier** [comment]
The Cardmarket API is offline.
i am eagerly waiting for it to come back.

https://www.cardmarket.com/de/Magic/News/Statement-On-Cardmarket-Outage
"Ebenso müssen wir folgende Funktionen bis auf weiteres deaktivieren:
- **Cardmarket API**
- Shopping-Wizard
- Bulk-Management Eures Inventars
- Verlinkte Accounts"

"Wir planen immer die Veröffentlichung der API 3.0 noch in diesem Jahr – dies wird ebenfalls zu größerer Stabilität und Performance beitragen."

**Comment by danielsundermeier** [comment]
Es gibt noch keine Veränderungen
