### ISSUE TITLE
Feature Request: Sync von unbezahlten bestellungen

### ISSUE THREAD

**Issue by KEEPSEVEN** [Cardmonitor/cardmonitor#218]
beim abgleich der bestellungen auf der seite
"Start -> Button Abgleich"

werden ebenfalls die "unbezahlten" bestellungen importiert.
Bei dem importvorgang wird, wie bei den bez. bestellungen, bereits die entsprechende karte auf die bestellung allokiert.

Implementierungsvorschlag:
auf der seite "Start" wird ein filter integriert. die auswahl ist "Unbezahlt" und "Bezahlt"
Standardvalue ist "Bezahlt".
![grafik](https://user-images.githubusercontent.com/126968762/223650436-32dd5477-4eb0-4b1d-9547-3453a8366b2a.png)

Es kann nun mithilfe des filters entweder die bez. bestellungen ode die unbezahlten bestellungen angezeigt/gefiltert werden.

Die pickliste triggert auf den filter d.h.
wenn ich den button "pickliste" mit dem filter "Unbezahlt" drücke, generiert mir cardmonitor eine pickliste für alle karten in den unbezahlten bestellungen

Hintergrund:
so können wir stornos einfach bearbeiten. wir sehen, welche karten auf die bestellung allokiert wurde, picken diese karten, und stornieren die bestellung auf cardmarket.

ein abgleich von stornos ist erst einmal nicht erforderlich (ggf. später) dann in einem separaten case.

**Comment by KEEPSEVEN** [comment]
edit: 
zweiter hintergrund.
für vor ort verkäufe ist der abgleich von unbezahlten bestellungen absolut erforderlich. cardmonitor kennt die karten nicht die unbezahlt sind. daher können karten vorort verkauft werden die bereits online verkauft wurden. ein doppelcheck ist nötig.

mit dieser funktion können vor einem verkauf die bestellungen abgeglichen werden. dann ist in cardmonitor sichtbar, welche karten tatsächlich noch verkaufbar sind. dieser abgleich wird händisch angetriggert. ein automatischer abgleich im hintergrund ist nicht erforderlich. (bis auf weiteres)

dieser abgleich kann dann nach bedarf durchgeführt werden.

**Comment by danielsundermeier** [comment]
Unbezahlte Bestellungen können jetzt synchronisiert werden, indem der Filter vor dem Synchrnonisieren auf "unbezahlt" gestellt wird.

Am Dienstag überspiele ich die Synchronisation der unbezahlten Bestellungen nach den Bezahlten.

**Comment by KEEPSEVEN** [comment]
top, so machen wir es, solange beibt es offen
