### ISSUE TITLE
Change Request: Orders export

### ISSUE THREAD

**Issue by KEEPSEVEN** [Cardmonitor/cardmonitor#220]
hinzufügen von Sprache und Zustand einer Karte in den "Cardname" String beim orders export.

zielzustand: es wird eine CSV generiert wie bisher, jedoch wird der Kartenname um 2 variablen erweitern

*Cardname* - *Grade* - *Language*

Beispiel: 
Bazaar of Baghdad - EX - English
Sorin the Mirthless (V.3)  - NM - English
Zurückhaltung - NM - German

Hintergrund: so haben wir im backendsystem in dem wir orders abwicklen, neben den kartennamen auch die sprache und den zustand und können dort den letzten quali check vollständig durchführen.

ebenso kommt es vereinzelnd vor, dass eine karte zwar in deutsch verkauft wurde jedoch in cardmonitor keine deutsche übersetzung vorhanden ist. in diesem fall kann aber jederzeit erkannt werden, dass die karte in "german" verkauft wurde

**Comment by danielsundermeier** [comment]
Foil auch?

**Comment by danielsundermeier** [comment]
Es gibt jetzt eine neue Spalte mit der Bezeichnung wie oben beschrieben nach "local_name"
Foil wird auch beachtet

**Comment by KEEPSEVEN** [comment]
check, CSV sieh gut aus. kann closed :)
