### ISSUE TITLE
Change Request: Einzel-Bestellseite optimieren

### ISSUE THREAD

**Issue by KEEPSEVEN** [Cardmonitor/cardmonitor#222]
Bis auf weiteres ausblenden der folgenden Komponenten.

diese können bei bedarf wieder nach und nach aktiviert werden, je nach dem wir die plattform dann genutzt werden soll/ weiterentwickelt wird.

derzeit brauchen wir folgenden funktionen nicht und können ausgeblendet werden:

Auf der Einzel-Bestellseite
- Die Bereiche: Bilder, Kalkulation, Kosten
damit rutscht der bereich "Artikel" weiter nach oben
Ebenso kommt dann der Button für den Exclude mit auf die seite.

die buttons oben rechts
- versenden

ebenso den "versenden" button auf der "bestell-gesamtübersicht" Tab "Bestellungen"

Alternativ: eine abfrage "Willst du wirklich versenden?"

wir versenden derzeit ausschl. über den import.

es kann ggf. passieren, dass man versehentlich die bestellung auf versendet setzt beim schnellen klicken.

**Comment by danielsundermeier** [comment]
Alles ausgeblendet.

**Comment by KEEPSEVEN** [comment]
sieht top aus, kann zu.
