### ISSUE TITLE
Bugfix: Import von Artikeln via TCG Power Tools import

### ISSUE THREAD

**Issue by KEEPSEVEN** [Cardmonitor/cardmonitor#225]
hat ein artikel kein "listedAt" so bricht der import der karten ab mit einer fehlermeldung.

gewünschtes verhalten:
der import läuft durch, es werden alle karten die kein datum haben, an den anfang gestellt, danach kommen alle karten sortiert nach dem datum wie gehabt.

CSV FILE:
"cardmarketId","quantity","name","set","setCode","cn","condition","language","isFoil","isPlayset","isSigned","price","comment","nameDE","nameES","nameFR","nameIT","rarity","listedAt"
"283349","1","Dwynen, Gilt-Leaf Daen","Magic Origins","ORI","172","GD","English","","","","150","","Dwynen, Güldenlaub-Daen","Dwynen, daena de Hojas Doradas","Dwynen, daen de Feuilledor","Dwynen, Daen di Foglia Dorata","Rare","22-03-2023 16:49:00"
"283349","1","Dwynen, Gilt-Leaf Daen","Magic Origins","ORI","172","GD","English","","","","150","","Dwynen, Güldenlaub-Daen","Dwynen, daena de Hojas Doradas","Dwynen, daen de Feuilledor","Dwynen, Daen di Foglia Dorata","Rare","22-03-2023 16:49:06"
"283349","1","Dwynen, Gilt-Leaf Daen","Magic Origins","ORI","172","GD","English","","","","150","","Dwynen, Güldenlaub-Daen","Dwynen, daena de Hojas Doradas","Dwynen, daen de Feuilledor","Dwynen, Daen di Foglia Dorata","Rare","22-03-2023 16:49:12"
"283349","1","Dwynen, Gilt-Leaf Daen","Magic Origins","ORI","172","GD","English","","","","150","","Dwynen, Güldenlaub-Daen","Dwynen, daena de Hojas Doradas","Dwynen, daen de Feuilledor","Dwynen, Daen di Foglia Dorata","Rare","22-03-2023 16:49:18"
"284472","1","Felidar Sovereign","Battle for Zendikar","BFZ","26","NM","English","","","","150","","Felidar-Herrscher","Felidar soberano","Souverain félidar","Sovrano dei Felidar","Rare","22-03-2023 16:45:10"
"288569","1","Gravecrawler","Duel Decks: Blessed vs. Cursed","DDQ","59","NM","English","","","","150","","Grabkriecher","Acechatumbas","Rampeur des tombes","Strisciante del Sepolcro","Rare"
"693271","1","Ichor Rats","Commander: Phyrexia: All Will Be One","ONC","93","NM","English","","","","150","","Wundsekret-Ratten","Ratas icóridas","Rats de sanie","Ratti dell'Icore","Uncommon","22-03-2023 16:47:27"
"290442","1","Imperious Perfect","Eternal Masters","EMA","173","GD","English","","","","150","","Gebieterischer Perfekter","Perfecta arrogante","Parfaite impérieuse","Perfetta Autoritaria","Rare","22-03-2023 16:49:29"
"290442","1","Imperious Perfect","Eternal Masters","EMA","173","GD","English","","","","150","","Gebieterischer Perfekter","Perfecta arrogante","Parfaite impérieuse","Perfetta Autoritaria","Rare","22-03-2023 16:49:40"
"290442","1","Imperious Perfect","Eternal Masters","EMA","173","GD","English","","","","150","","Gebieterischer Perfekter","Perfecta arrogante","Parfaite impérieuse","Perfetta Autoritaria","Rare","22-03-2023 16:49:48"
"290442","1","Imperious Perfect","Eternal Masters","EMA","173","GD","English","","","","150","","Gebieterischer Perfekter","Perfecta arrogante","Parfaite impérieuse","Perfetta Autoritaria","Rare","22-03-2023 16:49:56"
"662612","1","Puresteel Paladin","The List","ZNL","20","NM","English","","","","150","","Reinstahl-Paladin","Paladín de acero puro","Paladin de puracier","Paladino di Acciaio Puro","Rare","22-03-2023 16:46:49"
"532937","1","Resplendent Marshal","Kaldheim","KHM","22","NM","English","true","","","150","","Strahlende Marschallin","Mariscal fulgurante","Maréchale resplendissante","Marescialla Splendente","Mythic","22-03-2023 16:47:53"
"695308","1","Sword of Feast and Famine","The List","ZNL","296","NM","English","","","","150","","Schwert aus Schmaus und Hunger","Espada de abundancia y escasez","Épée de Festin et de Famine","Spada di Abbondanza e Carestia","Mythic","22-03-2023 16:47:10"
"673933","1","Vaevictis Asmadi, the Dire","The List","ZNL","225","NM","English","","","","150","","Vaevictis Asmadi, der Schreckliche","Vaevictis Asmadi, el Nefasto","Vaevictis Asmadi, le sinistre","Vaevictis Asmadi, il Funesto","Mythic","22-03-2023 16:47:42"

**Comment by danielsundermeier** [comment]
In der Datei war eine Spalte mehr als vorher.
Spalten werden jetzt dynamisch zugewiesen.

**Comment by KEEPSEVEN** [comment]
klappt nun einwandfrei
