### ISSUE TITLE
Change Request: Zusätzlicher Zustand bei WC Order abgleich

### ISSUE THREAD

**Issue by KEEPSEVEN** [Cardmonitor/cardmonitor#226]
Wir brauchen einen zusätzlichen Zustand der beim Import von "Orders" aus WC zu Cardmonitor erkannt wird.

Der Zustand soll "**Schlechter**" heißen und wird auf den Kartenzustand "**Poor**" gematcht.

![grafik](https://user-images.githubusercontent.com/126968762/227226474-14aafadb-6c6e-4e32-b67b-207aa13c4adc.png)

Gewünschter Zustand: Bei bestimmten Karten wird dem Kunden diese Auswahl zusätzlich angezeigt (das stellen wir auf der ankaufseite ein). Cardmonitor matched diesen Zustand dann auf Poor.

**Comment by danielsundermeier** [comment]
Wie besprochen:
Für die Zuordnung ist der Value verantwortlich.
Value muss "Poor (PO)" sein.

**Comment by KEEPSEVEN** [comment]
ok, testen wir, solange closed
