### ISSUE TITLE
Bug: Löschen/Anpassen von Artikel aus Cardmonitor heraus

### ISSUE THREAD

**Issue by KEEPSEVEN** [Cardmonitor/cardmonitor#229]
ab und zu kommt es vor, dass wir einen artikel händisch (über den mülleimer) aus cardmonitor und damit aus MKM löschen möchten.

in seltenen fällen kommt es zu einer fehlermeldung die besagt, dass der "datensatz" nicht vorhanden sei. Der artikel kann dann nicht gelöscht werden.

aktueller fix:
wolkensymbol mehrfach drücken damit der artikel neu in mkm angelegt wird. diesen dann wieder löschen, damit der artikel aus cardmarket wieder gelöscht wird.
dann den artikel, der noch in cardmarket vorhanden ist (der der nicht gesynct werden konnte) händische direkt aus cardmarket löschen.

scheinbar taucht dieser fehler "nur" bei artikel auf, welche vor dem livegang von cardmonitor angelegt wurden (über den artikel sync).
bei artikel, die von cardmonitor zu mkm geschickt wurden (nach dem livegang) ist dieser fehler bisher noch nicht aufgetreten.
da wir das "lösch szenario" derzeit aber selten haben, kann es auch ggf einfach noch nicht vorgekommen sein.

wir sollten das im auge behalten, vor allem sobald wir vor ort verkäufe haben. dann müssen wir ja karten händisch löschen können.

bei matchings im rahmen von orders gab es bisher keine probleme.

testkarten:

Otawara Lagernummer A003.117 hier tritt der fehler auf. die karte kann geöscht werden. zu testen/fallbeispiel haben wir die online gelassen mit einem hohen preis damit sie nicht noch mal verkauft wird.

**Comment by danielsundermeier** [comment]
Karten können nicht geklscht werden, wenn die Verknüpfung verloren gegangen ist. Die Cardmarket ID wird sich verändert haben und ist dann nicht mehr gleich.

**Comment by KEEPSEVEN** [comment]
Ok das macht sinn.
dann sollten wir ggf. den fokus auf die nummer im kommentar legen? würde das sozusagen als "fallback" lösung auch beim löschen klappen?

**Comment by KEEPSEVEN** [comment]
sind wir dran, kann closed werden.
